### ISSUE TITLE
vyos router not working

### ISSUE THREAD

**Issue by Narratot** [sandialabs/sceptre-phenix#173]
I an using the provided packer config for generating the vyos image. During the startup process of the vyos guest I get the information that the startup of the phenix processes failed. Furthermore it is currently not loading the router configuration.

**Comment by activeshadow** [comment]
@Narratot can you provide us with the specific information you're getting about the phenix processes failing? Or at least some details on how we can try to reproduce what you're seeing?

**Comment by Narratot** [comment]
I can build the vyos image successfully. During vyos startup I get the following error.
![Screenshot from 2024-02-29 09-33-19](https://github.com/sandialabs/sceptre-phenix/assets/36631236/b82cdd36-a0ff-42e3-a53d-03504cf74779)

**Comment by activeshadow** [comment]
Hi @Narratot can you also post your topology file please?

**Comment by Narratot** [comment]
@activeshadow sure.
```
apiVersion: phenix.sandia.gov/v1
kind: Topology
metadata:
  name: helloworld-router
  created: '2024-02-14T10:25:11+01:00'
  updated: '2024-03-01T09:34:34+01:00'
spec:
  nodes:
    - general:
        description: Test-Win
        hostname: Test
      hardware:
        drives:
          - image: W10-2.qc2
            inject_partition: 2
        memory: 16000
        os_type: windows
        vcpus: 8
      network:
        interfaces:
          - address: 192.168.1.11
            gateway: 192.168.1.254
            mask: 24
            name: if0
            proto: ospf
            type: ethernet
            vlan: SW1
      type: VirtualMachine
    - general:
        hostname: test2
      hardware:
        drives:
          - image: kali.qc2
        os_type: linux
      network:
        interfaces:
          - address: 192.168.1.12
            gateway: 192.168.1.254
            mask: 24
            name: if0
            proto: ospf
            type: ethernet
            vlan: SW1
      type: VirtualMachine
    - general:
        hostname: router
      hardware:
        drives:
          - image: minirouter.qc2
        os_type: minirouter
      network:
        interfaces:
          - address: 192.168.1.1
            mask: 30
            name: SW1
            proto: ospf
            type: ethernet
            vlan: SW1
        ospf:
          areas:
            - area_id: 0
              area_networks:
                - network: 192.168.1.1/24
          dead_interval: 60
          hello_interval: 10
          retrans_interval: 5
          router_id: 192.168.1.1
      type: Router
```
